media:
  input: assets/images
  output: /assets/images

content:
  - name: posts
    label: Posts
    type: collection
    path: _posts
    filename:
      template: "{year}-{month}-{day}-{title}.md"
      field: false
    fields:
      - name: layout
        type: string
        hidden: true
        default: post
      - name: title
        label: Title
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: published
        label: Published
        type: boolean
        default: true
      - name: tag_topic
        label: Topic Tags
        type: select
        options:
          multiple: true
          values:
            - ABC Costing
            - Dashboards
            - Drones
            - Ethics
            - Ethics Mindset
            - Interviewing
            - Process Mining
            - Professional Judgment
            - Soft Skills
            - Teaching Tools
            - Visualization
            - blockchain
      - name: tag_class
        label: Class Tags
        type: select
        options:
          multiple: true
          values:
            - Class AIS
            - Class Audit
            - Class Business
            - Class Cybersecurity
            - Class Data Analytics
            - Class Financial
            - Class Forensics
            - Class Management
            - Class Managerial
            - Class Personal Finance
            - Class Sustainability
            - Class Tax
      - name: tag_level
        label: Difficulty Level
        type: select
        options:
          multiple: true
          values:
            - Level Beginner
            - Level Intermediate
            - Level Advanced
      - name: tag_tools
        label: Tools & Tech
        type: select
        options:
          multiple: true
          values:
            - AI
            - Alteryx
            - Celonis
            - ChatGPT
            - DataSnipper
            - Database
            - Excel
            - GenAI
            - PowerBI
            - Python
            - R
            - RPA
            - RegEx
            - SQL
            - TIBCO Spotfire
            - Tableau
            - UiPath
            - VBA
      - name: tag_custom
        label: Custom Tags
        type: string
        list: true
      - name: body
        label: Content
        type: rich-text
