title: EYARC
description: "EY Academic Resource Center — free leading-edge accounting & data analytics resources for academics."
url: "https://ghpages.eyarc.site"
baseurl: ""
author:
  name: David Wood
  email: eyarc@ey.com
timezone: America/Denver
future: true
permalink: /blog/:title/
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
google_analytics: G-ZJ21NDWLQE
feed:
  path: feed.xml
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

exclude:
  - Gemfile
  - Gemfile.lock
  - migrate.py
  - "*.sh"
  - vendor/
